'forge.puppetlabs.com'
# install from Puppet Forge
mod 'puppetlabs/concat'
mod 'puppetlabs/ntp', '4.1.0'
mod 'puppet-nginx', '0.5.0'

# install from github
mod 'test',
:git => 'https://github.com/WaqasAh/test-work.git',
:tag => 'master'
